// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5_5OvcdLqwmv9AvUFlzu9OqLx_UuzxrY',
    appId: '1:623990508527:web:0b44cbbe5952977c18041a',
    messagingSenderId: '623990508527',
    projectId: 'password-manager-bab88',
    authDomain: 'password-manager-bab88.firebaseapp.com',
    storageBucket: 'password-manager-bab88.appspot.com',
    measurementId: 'G-JDCNZ9TT09',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgyHHpDMJ21UG-OsOfdvZaEw9bbtckjyM',
    appId: '1:623990508527:android:6e83d43fae61fd8718041a',
    messagingSenderId: '623990508527',
    projectId: 'password-manager-bab88',
    storageBucket: 'password-manager-bab88.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqI2NrG_JilhHwFybN8aU4u6--BfnH_d4',
    appId: '1:623990508527:ios:5a0e8ceb247e720518041a',
    messagingSenderId: '623990508527',
    projectId: 'password-manager-bab88',
    storageBucket: 'password-manager-bab88.appspot.com',
    iosBundleId: 'com.passwordmanager.passwordManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqI2NrG_JilhHwFybN8aU4u6--BfnH_d4',
    appId: '1:623990508527:ios:5a0e8ceb247e720518041a',
    messagingSenderId: '623990508527',
    projectId: 'password-manager-bab88',
    storageBucket: 'password-manager-bab88.appspot.com',
    iosBundleId: 'com.passwordmanager.passwordManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5_5OvcdLqwmv9AvUFlzu9OqLx_UuzxrY',
    appId: '1:623990508527:web:4e54b5297eb8064e18041a',
    messagingSenderId: '623990508527',
    projectId: 'password-manager-bab88',
    authDomain: 'password-manager-bab88.firebaseapp.com',
    storageBucket: 'password-manager-bab88.appspot.com',
    measurementId: 'G-EJ4EJMFTPV',
  );
}
